# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Open XDMoD Module for Open OnDemand log data
email: ccr-xdmod-help@buffalo.edu
description: >
  Open XDMoD Module for Open OnDemand log data allows the display and analysis
  of the usage of Open OnDemand in Open XDMoD. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ondemand.xdmod.org" # the base hostname & protocol for your site
github_username: ubccr
github_url: https://github.com/ubccr/xdmod-ondemand
xdmod_module_name: OnDemand
latest_version: "11.0"
latest_sw_version: "11.0.1"
version_list:
  - "11.0"
  - "10.5"
unsupported_version_list:
  - "10.0"
  - "9.5"

defaults:
  -
    scope:
      path: "11.0"
      type: "pages"
    values:
      layout: "page"
      version: "11.0"
      sw_version: "11.0.1"
      rpm_version: "11.0.1-1"
      style: "effervescence"
      tocversion: "v11_0toc"
  -
    scope:
      path: "10.5"
      type: "pages"
    values:
      layout: "page"
      version: "10.5"
      sw_version: "10.5.1"
      style: "effervescence"
      tocversion: "v10_5toc"
  -
    scope:
      path: "10.0"
      type: "pages"
    values:
      layout: "page"
      version: "10.0"
      sw_version: "10.0.0"
      style: "effervescence"
      tocversion: "v10_0toc"
  -
    scope:
      path: "9.5"
      type: "pages"
    values:
      layout: "page"
      version: "9.5"
      sw_version: "9.5.0"
      style: "effervescence"
      tocversion: "v9_5toc"

# Build settings
markdown: kramdown
theme_subdir: "/xdmod-jekyll-theme"
gems:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
